image: google/cloud-sdk

stages:
  - testbuild
  - buildpush

test:
  stage: testbuild
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest tests/test_roman.py --verbose

push:
  stage: buildpush
  script:
    - echo $GCLOUD_JSON > credentials.json
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - gcloud auth activate-service-account --key-file credentials.json
    - gcloud app deploy --quiet --project=roman-flask-app
  only:
    - master
