image: google/cloud-sdk

stages:
  - testbuild
  - buildpush

test:
  stage: testbuild
  script:
    - add-apt-repository ppa:deadsnakes/ppa
    - apt-get update
    - apt-get install python3.6
    - virtualenv -p $(which python3.6) venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest tests/test_roman.py --verbose

push:
  stage: buildpush
  script:
    - echo $GCLOUD_JSON > credentials.json
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - gcloud auth activate-service-account --key-file credentials.json
    - gcloud app deploy --quiet --project=roman-flask-app
  only:
    - master
